// src/app/components/AuditPanel.svelte
<script lang="ts">
import { getAuditStats } from "../../auditor/index.js";
import type { AuditFlag } from "../../types/index.js";
import {
  Badge,
  Button,
  CollapsibleSection,
  DiagnosticItem,
  Input,
  SectionPanel,
  SegmentedBar,
} from "../primitives/index.js";

let {
  flags,
  onResolve,
  onDismiss,
}: {
  flags: AuditFlag[];
  onResolve: (flagId: string, action: string) => void;
  onDismiss: (flagId: string) => void;
} = $props();

let resolveInput = $state<Record<string, string>>({});

let stats = $derived(getAuditStats(flags));
let critical = $derived(flags.filter((f) => f.severity === "critical" && !f.resolved));
let warnings = $derived(flags.filter((f) => f.severity === "warning" && !f.resolved));
let infos = $derived(flags.filter((f) => f.severity === "info" && !f.resolved));
let resolved = $derived(flags.filter((f) => f.resolved));

function handleResolve(flagId: string) {
  const action = resolveInput[flagId] ?? "";
  if (!action.trim()) return;
  onResolve(flagId, action);
  const next = { ...resolveInput };
  delete next[flagId];
  resolveInput = next;
}
</script>

<SectionPanel title="Audit">
  {#snippet badge()}<span class="audit-summary">{stats.pending} pending | {Math.round(stats.signalToNoiseRatio * 100)}% actionable</span>{/snippet}

  {#if stats.total > 0 && stats.actionable + stats.nonActionable > 0}
    <div class="signal-meter">
      <SegmentedBar
        segments={[
          ...(stats.actionable > 0 ? [{ label: `${stats.actionable} actionable`, flex: stats.actionable, variant: "actionable" }] : []),
          ...(stats.nonActionable > 0 ? [{ label: `${stats.nonActionable} noise`, flex: stats.nonActionable, variant: "noise" }] : []),
        ]}
        height={8}
      />
      <div class="signal-label">
        {stats.actionable} actionable / {stats.nonActionable} noise
        {#if stats.signalToNoiseRatio < 0.6} — below 60% target{/if}
      </div>
    </div>
  {/if}

  {#if flags.length === 0}
    <div class="audit-empty">No audit flags. Run an audit after generating chunks.</div>
  {/if}

  {#each critical as flag (flag.id)}
    {@render auditFlag(flag)}
  {/each}
  {#each warnings as flag (flag.id)}
    {@render auditFlag(flag)}
  {/each}
  {#each infos as flag (flag.id)}
    {@render auditFlag(flag)}
  {/each}

  {#if resolved.length > 0}
    <CollapsibleSection summary="{resolved.length} resolved">
      {#each resolved as flag (flag.id)}
        <div class="resolved-flag">
          <DiagnosticItem severity={flag.severity} message="[{flag.category}] {flag.message}">
            {#snippet actions()}
              {#if flag.resolvedAction}
                <span class="resolved-action">Action: {flag.resolvedAction}</span>
              {/if}
              <Badge>{flag.wasActionable ? "actionable" : "dismissed"}</Badge>
            {/snippet}
          </DiagnosticItem>
        </div>
      {/each}
    </CollapsibleSection>
  {/if}

  {#if Object.keys(stats.byCategory).length > 0}
    <CollapsibleSection summary="Category breakdown">
      <div class="category-list">
        {#each Object.entries(stats.byCategory) as [cat, data]}
          <div>{cat}: {data.total} total, {data.actionable} actionable</div>
        {/each}
      </div>
    </CollapsibleSection>
  {/if}
</SectionPanel>

{#snippet auditFlag(flag: AuditFlag)}
  <DiagnosticItem severity={flag.severity} message="[{flag.category}] {flag.message}{flag.lineReference ? ` (${flag.lineReference})` : ''}">
    {#snippet actions()}
      {#if !flag.resolved}
        <Input
          placeholder="What did you do?"
          value={resolveInput[flag.id] ?? ""}
          oninput={(e) => { resolveInput = { ...resolveInput, [flag.id]: (e.target as HTMLInputElement).value }; }}
          onkeydown={(e) => { if (e.key === "Enter") handleResolve(flag.id); }}
        />
        <Button size="sm" onclick={() => handleResolve(flag.id)}>Resolve</Button>
        <Button size="sm" onclick={() => onDismiss(flag.id)}>Dismiss</Button>
      {/if}
    {/snippet}
  </DiagnosticItem>
{/snippet}

<style>
  .audit-summary { font-size: 10px; }
  .signal-meter { padding: 4px 0; margin-bottom: 6px; }
  .signal-label { font-size: 9px; color: var(--text-muted); margin-top: 2px; }
  .audit-empty { color: var(--text-muted); font-size: 11px; padding: 8px 0; }
  .resolved-flag { opacity: 0.5; }
  .resolved-action { font-size: 10px; color: var(--text-muted); }
  .category-list { font-size: 10px; padding: 4px 0; color: var(--text-secondary); }
</style>

// src/app/components/AuditPanel.tsx
import { useMemo, useState } from "react";
import { getAuditStats } from "../../auditor/index.js";
import type { AuditFlag, AuditStats } from "../../types/index.js";

interface Props {
  flags: AuditFlag[];
  onResolve: (flagId: string, action: string) => void;
  onDismiss: (flagId: string) => void;
}

export function AuditPanel({ flags, onResolve, onDismiss }: Props) {
  const [resolveInput, setResolveInput] = useState<Record<string, string>>({});

  const stats: AuditStats = useMemo(() => getAuditStats(flags), [flags]);

  const critical = flags.filter((f) => f.severity === "critical" && !f.resolved);
  const warnings = flags.filter((f) => f.severity === "warning" && !f.resolved);
  const infos = flags.filter((f) => f.severity === "info" && !f.resolved);
  const resolved = flags.filter((f) => f.resolved);

  const handleResolve = (flagId: string) => {
    const action = resolveInput[flagId] ?? "";
    if (!action.trim()) return;
    onResolve(flagId, action);
    setResolveInput((prev) => {
      const next = { ...prev };
      delete next[flagId];
      return next;
    });
  };

  const renderFlag = (flag: AuditFlag) => (
    <div key={flag.id} className={`audit-flag audit-${flag.severity}`}>
      <div style={{ display: "flex", justifyContent: "space-between", alignItems: "flex-start" }}>
        <div>
          <strong>[{flag.category}]</strong> {flag.message}
          {flag.lineReference && <span style={{ color: "var(--text-muted)" }}> ({flag.lineReference})</span>}
        </div>
      </div>
      {!flag.resolved && (
        <div style={{ marginTop: "6px", display: "flex", gap: "4px", alignItems: "center" }}>
          <input
            type="text"
            placeholder="What did you do?"
            value={resolveInput[flag.id] ?? ""}
            onChange={(e) => setResolveInput((prev) => ({ ...prev, [flag.id]: e.target.value }))}
            onKeyDown={(e) => e.key === "Enter" && handleResolve(flag.id)}
            style={{
              flex: 1,
              fontFamily: "var(--font-mono)",
              fontSize: "10px",
              padding: "3px 6px",
              background: "var(--bg-input)",
              border: "1px solid var(--border)",
              borderRadius: "3px",
              color: "var(--text-primary)",
            }}
          />
          <button style={{ fontSize: "9px" }} onClick={() => handleResolve(flag.id)}>
            Resolve
          </button>
          <button style={{ fontSize: "9px" }} onClick={() => onDismiss(flag.id)}>
            Dismiss
          </button>
        </div>
      )}
    </div>
  );

  return (
    <div className="compiler-section">
      <div className="compiler-section-header">
        <span>Audit</span>
        <span style={{ fontSize: "10px" }}>
          {stats.pending} pending | {Math.round(stats.signalToNoiseRatio * 100)}% actionable
        </span>
      </div>

      {/* Signal-to-noise meter */}
      {stats.total > 0 && stats.actionable + stats.nonActionable > 0 && (
        <div style={{ padding: "4px 0", marginBottom: "6px" }}>
          <div
            style={{
              display: "flex",
              gap: "2px",
              height: "8px",
              borderRadius: "4px",
              overflow: "hidden",
            }}
          >
            <div
              style={{
                flex: stats.actionable,
                background: "var(--success)",
              }}
            />
            <div
              style={{
                flex: stats.nonActionable,
                background: "var(--warning)",
              }}
            />
          </div>
          <div style={{ fontSize: "9px", color: "var(--text-muted)", marginTop: "2px" }}>
            {stats.actionable} actionable / {stats.nonActionable} noise
            {stats.signalToNoiseRatio < 0.6 && " — below 60% target"}
          </div>
        </div>
      )}

      {flags.length === 0 && (
        <div style={{ color: "var(--text-muted)", fontSize: "11px", padding: "8px 0" }}>
          No audit flags. Run an audit after generating chunks.
        </div>
      )}

      {critical.length > 0 && critical.map(renderFlag)}
      {warnings.length > 0 && warnings.map(renderFlag)}
      {infos.length > 0 && infos.map(renderFlag)}

      {resolved.length > 0 && (
        <details style={{ marginTop: "8px" }}>
          <summary style={{ fontSize: "10px", color: "var(--text-muted)", cursor: "pointer" }}>
            {resolved.length} resolved
          </summary>
          {resolved.map((flag) => (
            <div key={flag.id} className="audit-flag" style={{ opacity: 0.5 }}>
              <strong>[{flag.category}]</strong> {flag.message}
              {flag.resolvedAction && (
                <div style={{ fontSize: "10px", color: "var(--text-muted)" }}>Action: {flag.resolvedAction}</div>
              )}
              <span className="badge" style={{ marginLeft: "4px" }}>
                {flag.wasActionable ? "actionable" : "dismissed"}
              </span>
            </div>
          ))}
        </details>
      )}

      {/* Per-category breakdown */}
      {Object.keys(stats.byCategory).length > 0 && (
        <details style={{ marginTop: "8px" }}>
          <summary style={{ fontSize: "10px", color: "var(--text-muted)", cursor: "pointer" }}>
            Category breakdown
          </summary>
          <div style={{ fontSize: "10px", padding: "4px 0" }}>
            {Object.entries(stats.byCategory).map(([cat, data]) => (
              <div key={cat} style={{ color: "var(--text-secondary)" }}>
                {cat}: {data.total} total, {data.actionable} actionable
              </div>
            ))}
          </div>
        </details>
      )}
    </div>
  );
}
