// src/app/components/BiblePane.svelte
<script lang="ts">
import { json } from "@codemirror/lang-json";
import { oneDark } from "@codemirror/theme-one-dark";
import CodeMirror from "svelte-codemirror-editor";
import type { Bible, ChapterArc, ScenePlan } from "../../types/index.js";
import { Button, Pane } from "../primitives/index.js";
import type { ProjectStore } from "../store/project.svelte.js";

let {
  store,
  onBootstrap,
  onAuthor,
}: {
  store: ProjectStore;
  onBootstrap: () => void;
  onAuthor?: () => void;
} = $props();

let bibleJson = $derived(store.bible ? JSON.stringify(store.bible, null, 2) : "");
let planJson = $derived(store.activeScenePlan ? JSON.stringify(store.activeScenePlan, null, 2) : "");

const extensions = [json(), oneDark];

function handleBibleChange(text: string) {
  try {
    const parsed = JSON.parse(text) as Bible;
    store.setBible(parsed);
  } catch {
    // Invalid JSON — don't update state until valid
  }
}

function handlePlanChange(text: string) {
  try {
    const parsed = JSON.parse(text) as ScenePlan;
    if (store.activeScenePlan) {
      // Update the active scene plan in place
      store.addScenePlan(parsed);
    } else {
      store.setScenePlan(parsed);
    }
  } catch {
    // Invalid JSON
  }
}

async function handleLoadBible() {
  const text = await store.loadFile();
  if (text) {
    try {
      const parsed = JSON.parse(text) as Bible;
      store.setBible(parsed);
    } catch {
      store.setError("Invalid Bible JSON");
    }
  }
}

async function handleLoadPlan() {
  const text = await store.loadFile();
  if (text) {
    try {
      const parsed = JSON.parse(text) as ScenePlan;
      if (store.scenes.length > 0) {
        store.addScenePlan(parsed);
      } else {
        store.setScenePlan(parsed);
      }
    } catch {
      store.setError("Invalid Scene Plan JSON");
    }
  }
}

async function handleLoadArc() {
  const text = await store.loadFile();
  if (text) {
    try {
      const parsed = JSON.parse(text) as ChapterArc;
      store.setChapterArc(parsed);
    } catch {
      store.setError("Invalid Chapter Arc JSON");
    }
  }
}
</script>

<Pane title="Bible + Plan" contentClass="bible-content">
  {#snippet headerRight()}
    <div class="pane-actions">
      {#if onAuthor}
        <Button onclick={onAuthor}>New Bible</Button>
      {:else}
        <Button onclick={onBootstrap}>Bootstrap</Button>
      {/if}
    </div>
  {/snippet}
    <div class="bible-buttons">
      <Button onclick={handleLoadBible}>Load Bible</Button>
      <Button onclick={() => store.bible && store.saveFile(store.bible, "bible.json")} disabled={!store.bible}>Save Bible</Button>
      <Button onclick={handleLoadPlan}>Load Plan</Button>
      <Button onclick={() => store.activeScenePlan && store.saveFile(store.activeScenePlan, "scene-plan.json")} disabled={!store.activeScenePlan}>Save Plan</Button>
      <Button onclick={handleLoadArc}>Load Arc</Button>
      {#if store.bible}
        <span class="bible-version">v{store.bible.version}</span>
      {/if}
    </div>
    <div class="editor-section">
      <div class="editor-label">Bible JSON</div>
      <div class="editor-wrapper">
        <CodeMirror value={bibleJson} on:change={(e) => handleBibleChange(e.detail)} {extensions} />
      </div>
    </div>
    <div class="editor-section">
      <div class="editor-label">Scene Plan JSON</div>
      <div class="editor-wrapper">
        <CodeMirror value={planJson} on:change={(e) => handlePlanChange(e.detail)} {extensions} />
      </div>
    </div>
</Pane>

<style>
  :global(.bible-content) { display: flex; flex-direction: column; gap: 8px; }
  .bible-buttons { display: flex; gap: 4px; flex-wrap: wrap; align-items: center; }
  .bible-version { font-size: 10px; color: var(--accent-dim); margin-left: auto; }
  .editor-section { display: flex; flex-direction: column; flex: 1; min-height: 0; }
  .editor-label {
    padding: 4px 8px; font-size: 10px; text-transform: uppercase; letter-spacing: 0.1em;
    color: var(--text-muted); background: var(--bg-secondary); border-bottom: 1px solid var(--border);
  }
  .editor-wrapper { flex: 1; overflow: hidden; border: 1px solid var(--border); border-radius: var(--radius-md); }
</style>

// src/app/components/BiblePane.tsx
import { defaultKeymap, history, historyKeymap } from "@codemirror/commands";
import { json } from "@codemirror/lang-json";
import { bracketMatching, foldGutter } from "@codemirror/language";
import { EditorState } from "@codemirror/state";
import { oneDark } from "@codemirror/theme-one-dark";
import { EditorView, keymap, lineNumbers } from "@codemirror/view";
import React, { useCallback, useEffect, useRef } from "react";
import type { Bible, ScenePlan } from "../../types/index.js";
import type { AppAction } from "../hooks/useProject.js";

interface Props {
  bible: Bible | null;
  scenePlan: ScenePlan | null;
  dispatch: React.Dispatch<AppAction>;
  loadFile: () => Promise<string | null>;
  saveFile: (data: unknown, filename: string) => void;
  onBootstrap: () => void;
}

function JsonEditor({ value, onChange, label }: { value: string; onChange: (val: string) => void; label: string }) {
  const containerRef = useRef<HTMLDivElement>(null);
  const viewRef = useRef<EditorView | null>(null);
  const onChangeRef = useRef(onChange);
  onChangeRef.current = onChange;

  useEffect(() => {
    if (!containerRef.current) return;

    const state = EditorState.create({
      doc: value,
      extensions: [
        json(),
        oneDark,
        lineNumbers(),
        bracketMatching(),
        foldGutter(),
        history(),
        keymap.of([...defaultKeymap, ...historyKeymap]),
        EditorView.updateListener.of((update) => {
          if (update.docChanged) {
            onChangeRef.current(update.state.doc.toString());
          }
        }),
        EditorView.theme({
          "&": { height: "100%" },
          ".cm-scroller": { overflow: "auto" },
        }),
      ],
    });

    const view = new EditorView({ state, parent: containerRef.current });
    viewRef.current = view;

    return () => {
      view.destroy();
    };
    // Only create on mount — value updates handled below
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [value]);

  // Sync external value changes (e.g., file load)
  useEffect(() => {
    const view = viewRef.current;
    if (!view) return;
    const current = view.state.doc.toString();
    if (current !== value) {
      view.dispatch({
        changes: { from: 0, to: current.length, insert: value },
      });
    }
  }, [value]);

  return (
    <div className="editor-section">
      <div className="editor-label">{label}</div>
      <div className="editor-wrapper" ref={containerRef} />
    </div>
  );
}

export function BiblePane({ bible, scenePlan, dispatch, loadFile, saveFile, onBootstrap }: Props) {
  const bibleJson = bible ? JSON.stringify(bible, null, 2) : "";
  const planJson = scenePlan ? JSON.stringify(scenePlan, null, 2) : "";

  const handleBibleChange = useCallback(
    (text: string) => {
      try {
        const parsed = JSON.parse(text) as Bible;
        dispatch({ type: "SET_BIBLE", bible: parsed });
      } catch {
        // Invalid JSON — don't update state until valid
      }
    },
    [dispatch],
  );

  const handlePlanChange = useCallback(
    (text: string) => {
      try {
        const parsed = JSON.parse(text) as ScenePlan;
        dispatch({ type: "SET_SCENE_PLAN", plan: parsed });
      } catch {
        // Invalid JSON
      }
    },
    [dispatch],
  );

  const handleLoadBible = useCallback(async () => {
    const text = await loadFile();
    if (text) {
      try {
        const parsed = JSON.parse(text) as Bible;
        dispatch({ type: "SET_BIBLE", bible: parsed });
      } catch {
        dispatch({ type: "SET_ERROR", error: "Invalid Bible JSON" });
      }
    }
  }, [loadFile, dispatch]);

  const handleLoadPlan = useCallback(async () => {
    const text = await loadFile();
    if (text) {
      try {
        const parsed = JSON.parse(text) as ScenePlan;
        dispatch({ type: "SET_SCENE_PLAN", plan: parsed });
      } catch {
        dispatch({ type: "SET_ERROR", error: "Invalid Scene Plan JSON" });
      }
    }
  }, [loadFile, dispatch]);

  return (
    <div className="pane">
      <div className="pane-header">
        <span>Bible + Plan</span>
        <div className="pane-actions">
          <button onClick={onBootstrap}>Bootstrap</button>
        </div>
      </div>
      <div className="pane-content" style={{ display: "flex", flexDirection: "column", gap: "8px" }}>
        <div style={{ display: "flex", gap: "4px", flexWrap: "wrap", alignItems: "center" }}>
          <button onClick={handleLoadBible}>Load Bible</button>
          <button onClick={() => bible && saveFile(bible, "bible.json")} disabled={!bible}>
            Save Bible
          </button>
          <button onClick={handleLoadPlan}>Load Plan</button>
          <button onClick={() => scenePlan && saveFile(scenePlan, "scene-plan.json")} disabled={!scenePlan}>
            Save Plan
          </button>
          {bible && (
            <span style={{ fontSize: "10px", color: "var(--accent-dim)", marginLeft: "auto" }}>v{bible.version}</span>
          )}
        </div>
        <JsonEditor value={bibleJson} onChange={handleBibleChange} label="Bible JSON" />
        <JsonEditor value={planJson} onChange={handlePlanChange} label="Scene Plan JSON" />
      </div>
    </div>
  );
}
