// src/app/components/BootstrapModal.svelte
<script lang="ts">
import { bootstrapToBible, buildBootstrapPrompt, parseBootstrapResponse } from "../../bootstrap/index.js";
import { generateStream } from "../../llm/client.js";
import { Button, ErrorBanner, Modal, Spinner, TextArea } from "../primitives/index.js";
import type { ProjectStore } from "../store/project.svelte.js";

let {
  store,
}: {
  store: ProjectStore;
} = $props();

let synopsis = $state("");
let loading = $state(false);
let status = $state("");
let streamText = $state("");
let elapsed = $state(0);
let error = $state<string | null>(null);
let timerRef: ReturnType<typeof setInterval> | null = null;

function handleClose() {
  store.setBootstrapOpen(false);
  error = null;
  status = "";
  streamText = "";
  elapsed = 0;
  if (timerRef) clearInterval(timerRef);
}

async function handleBootstrap() {
  if (!synopsis.trim()) return;

  loading = true;
  error = null;
  streamText = "";
  elapsed = 0;

  const started = Date.now();
  timerRef = setInterval(() => {
    elapsed = Math.floor((Date.now() - started) / 1000);
  }, 1000);

  try {
    status = "Building prompt...";
    const payload = buildBootstrapPrompt(synopsis);

    status = "Streaming from LLM...";
    let fullText = "";

    await generateStream(payload, {
      onToken: (text) => {
        fullText += text;
        streamText = fullText;
      },
      onDone: () => {
        status = "Parsing response...";
      },
      onError: (err) => {
        throw new Error(err);
      },
    });

    const parsed = parseBootstrapResponse(fullText);
    if ("error" in parsed) {
      error = `Parse failed: ${parsed.error}\n\nRaw response:\n${fullText.slice(0, 500)}`;
      loading = false;
      status = "";
      return;
    }

    const bible = bootstrapToBible(parsed, `proj-${Date.now()}`);
    status = "Done!";
    store.setBible(bible);

    setTimeout(() => {
      store.setBootstrapOpen(false);
      loading = false;
      status = "";
      streamText = "";
      elapsed = 0;
    }, 600);
  } catch (err) {
    error = err instanceof Error ? err.message : "Bootstrap failed";
    loading = false;
    status = "";
  } finally {
    if (timerRef) clearInterval(timerRef);
  }
}
</script>

<Modal open={store.bootstrapModalOpen} onClose={handleClose}>
  {#snippet header()}Bootstrap Bible from Synopsis{/snippet}

  <p class="modal-instructions">
    Paste your story synopsis. The system will extract characters, locations, tone, and a suggested kill list.
    You'll need to add dialogue samples manually.
  </p>

  {#if !loading}
    <TextArea
      bind:value={synopsis}
      placeholder={`Example synopsis — replace with your own:\n\nMarcus Cole, a retired homicide detective turned bar owner, runs a dimly lit jazz bar called "The Velvet" in a decaying waterfront district...`}
    />
  {:else}
    <div class="stream-display">{streamText || "Waiting for first token..."}</div>
  {/if}

  {#if loading}
    <div class="status-bar">
      <Spinner size="sm" />
      <span>{status}</span>
      <span class="status-meta">{elapsed}s · {streamText.length} chars</span>
    </div>
  {/if}

  {#if error}
    <div class="modal-error-wrap">
      <ErrorBanner message={error} />
    </div>
  {/if}

  {#snippet footer()}
    <Button onclick={handleClose}>Cancel</Button>
    <Button variant="primary" onclick={handleBootstrap} disabled={loading || !synopsis.trim()}>
      {loading ? "Bootstrapping..." : "Bootstrap Bible"}
    </Button>
  {/snippet}
</Modal>

<style>
  .modal-instructions { margin-bottom: 12px; color: var(--text-secondary); font-size: 12px; }
  .stream-display {
    font-family: var(--font-mono); font-size: 11px; background: var(--bg-input);
    border: 1px solid var(--border); border-radius: var(--radius-md); padding: 8px; height: 300px;
    overflow: auto; white-space: pre-wrap; word-break: break-word; color: var(--text-primary);
  }
  .status-bar {
    margin-top: 8px; padding: 6px 10px; border-radius: var(--radius-md); font-size: 11px;
    display: flex; align-items: center; gap: 8px;
  }
  .status-meta { color: var(--text-secondary); margin-left: auto; }
  .modal-error-wrap { margin-top: 8px; }
  .modal-error-wrap :global(.error-banner) { white-space: pre-wrap; }
</style>

// src/app/components/BootstrapModal.tsx
import React, { useCallback, useRef, useState } from "react";
import { bootstrapToBible, buildBootstrapPrompt, parseBootstrapResponse } from "../../bootstrap/index.js";
import { generateStream } from "../../llm/client.js";
import type { AppAction } from "../hooks/useProject.js";

interface Props {
  open: boolean;
  dispatch: React.Dispatch<AppAction>;
}

export function BootstrapModal({ open, dispatch }: Props) {
  const [synopsis, setSynopsis] = useState("");
  const [loading, setLoading] = useState(false);
  const [status, setStatus] = useState("");
  const [streamText, setStreamText] = useState("");
  const [elapsed, setElapsed] = useState(0);
  const [error, setError] = useState<string | null>(null);
  const timerRef = useRef<ReturnType<typeof setInterval> | null>(null);

  const handleClose = useCallback(() => {
    dispatch({ type: "SET_BOOTSTRAP_OPEN", value: false });
    setError(null);
    setStatus("");
    setStreamText("");
    setElapsed(0);
    if (timerRef.current) clearInterval(timerRef.current);
  }, [dispatch]);

  const handleBootstrap = useCallback(async () => {
    if (!synopsis.trim()) return;

    setLoading(true);
    setError(null);
    setStreamText("");
    setElapsed(0);

    const started = Date.now();
    timerRef.current = setInterval(() => {
      setElapsed(Math.floor((Date.now() - started) / 1000));
    }, 1000);

    try {
      setStatus("Building prompt...");
      const payload = buildBootstrapPrompt(synopsis);

      setStatus("Streaming from LLM...");
      let fullText = "";

      await generateStream(payload, {
        onToken: (text) => {
          fullText += text;
          setStreamText(fullText);
        },
        onDone: () => {
          setStatus("Parsing response...");
        },
        onError: (err) => {
          throw new Error(err);
        },
      });

      const parsed = parseBootstrapResponse(fullText);
      if ("error" in parsed) {
        setError(`Parse failed: ${parsed.error}\n\nRaw response:\n${fullText.slice(0, 500)}`);
        setLoading(false);
        setStatus("");
        return;
      }

      const bible = bootstrapToBible(parsed, `proj-${Date.now()}`);
      setStatus("Done!");
      dispatch({ type: "SET_BIBLE", bible });

      setTimeout(() => {
        dispatch({ type: "SET_BOOTSTRAP_OPEN", value: false });
        setLoading(false);
        setStatus("");
        setStreamText("");
        setElapsed(0);
      }, 600);
    } catch (err) {
      setError(err instanceof Error ? err.message : "Bootstrap failed");
      setLoading(false);
      setStatus("");
    } finally {
      if (timerRef.current) clearInterval(timerRef.current);
    }
  }, [synopsis, dispatch]);

  if (!open) return null;

  return (
    <div className="modal-overlay" onClick={handleClose}>
      <div className="modal" onClick={(e) => e.stopPropagation()}>
        <div className="modal-header">Bootstrap Bible from Synopsis</div>
        <div className="modal-body">
          <p style={{ marginBottom: "12px", color: "var(--text-secondary)", fontSize: "12px" }}>
            Paste your story synopsis. The system will extract characters, locations, tone, and a suggested kill list.
            You'll need to add dialogue samples manually.
          </p>

          {!loading ? (
            <textarea
              value={synopsis}
              onChange={(e) => setSynopsis(e.target.value)}
              placeholder={`Example synopsis — replace with your own:\n\nMarcus Cole, a retired homicide detective turned bar owner, runs a dimly lit jazz bar called "The Velvet" in a decaying waterfront district. He speaks in clipped, world-weary sentences and never uses metaphors — he says what he means. His bartender Elena Voss is a sharp-tongued grad student working nights to pay tuition; she speaks in long, winding sentences full of literary references that annoy Marcus.\n\nOne rainy Tuesday, a woman named Claire Fontaine walks in asking about a man who died in the bar six months ago — a death ruled accidental that Marcus has always suspected was murder. Claire claims to be the dead man's sister, but Marcus notices she never says his name.\n\nThe story is close-third POV through Marcus. The prose should feel like late-period Raymond Carver crossed with Dennis Lehane — spare, muscular sentences with sudden moments of surprising tenderness. No flowery language. No adverbs modifying dialogue tags. The bar smells like old wood, spilled bourbon, and rain. The jukebox plays Coltrane.\n\nThe scene takes place entirely inside the bar over about 45 minutes of story time. The tension is in what isn't said — Claire is testing Marcus and Marcus knows it, but he plays along because he wants answers too.`}
            />
          ) : (
            <div
              style={{
                fontFamily: "var(--font-mono)",
                fontSize: "11px",
                background: "var(--bg-input)",
                border: "1px solid var(--border)",
                borderRadius: "4px",
                padding: "8px",
                height: "300px",
                overflow: "auto",
                whiteSpace: "pre-wrap",
                wordBreak: "break-word",
                color: "var(--text-primary)",
              }}
            >
              {streamText || "Waiting for first token..."}
            </div>
          )}

          {loading && (
            <div
              style={{
                marginTop: "8px",
                padding: "6px 10px",
                background: "var(--bg-tertiary)",
                borderRadius: "4px",
                fontSize: "11px",
                display: "flex",
                alignItems: "center",
                gap: "8px",
              }}
            >
              <span className="spinner" style={{ width: "10px", height: "10px" }} />
              <span style={{ color: "var(--text-primary)" }}>{status}</span>
              <span style={{ color: "var(--text-secondary)", marginLeft: "auto" }}>
                {elapsed}s · {streamText.length} chars
              </span>
            </div>
          )}

          {error && (
            <div className="error-banner" style={{ marginTop: "8px", whiteSpace: "pre-wrap" }}>
              {error}
            </div>
          )}
        </div>
        <div className="modal-footer">
          <button onClick={handleClose}>Cancel</button>
          <button className="primary" onClick={handleBootstrap} disabled={loading || !synopsis.trim()}>
            {loading ? "Bootstrapping..." : "Bootstrap Bible"}
          </button>
        </div>
      </div>
    </div>
  );
}
