// src/app/components/ChapterArcEditor.tsx
import React, { useCallback } from "react";
import type { ChapterArc, ReaderState } from "../../types/index.js";
import type { AppAction } from "../hooks/useProject.js";

interface Props {
  arc: ChapterArc;
  dispatch: React.Dispatch<AppAction>;
  onClose: () => void;
}

function ReaderStateFields({
  label,
  state,
  onChange,
}: {
  label: string;
  state: ReaderState;
  onChange: (rs: ReaderState) => void;
}) {
  return (
    <fieldset className="arc-fieldset">
      <legend>{label}</legend>
      <label>
        Knows
        <input
          type="text"
          value={state.knows.join(", ")}
          onChange={(e) =>
            onChange({
              ...state,
              knows: e.target.value
                .split(",")
                .map((s) => s.trim())
                .filter(Boolean),
            })
          }
          placeholder="Comma-separated items"
        />
      </label>
      <label>
        Suspects
        <input
          type="text"
          value={state.suspects.join(", ")}
          onChange={(e) =>
            onChange({
              ...state,
              suspects: e.target.value
                .split(",")
                .map((s) => s.trim())
                .filter(Boolean),
            })
          }
          placeholder="Comma-separated items"
        />
      </label>
      <label>
        Wrong about
        <input
          type="text"
          value={state.wrongAbout.join(", ")}
          onChange={(e) =>
            onChange({
              ...state,
              wrongAbout: e.target.value
                .split(",")
                .map((s) => s.trim())
                .filter(Boolean),
            })
          }
          placeholder="Comma-separated items"
        />
      </label>
      <label>
        Active tensions
        <input
          type="text"
          value={state.activeTensions.join(", ")}
          onChange={(e) =>
            onChange({
              ...state,
              activeTensions: e.target.value
                .split(",")
                .map((s) => s.trim())
                .filter(Boolean),
            })
          }
          placeholder="Comma-separated items"
        />
      </label>
    </fieldset>
  );
}

export function ChapterArcEditor({ arc, dispatch, onClose }: Props) {
  const update = useCallback(
    (changes: Partial<ChapterArc>) => {
      dispatch({ type: "SET_CHAPTER_ARC", arc: { ...arc, ...changes } });
    },
    [arc, dispatch],
  );

  return (
    <div className="modal-overlay" onClick={onClose}>
      <div className="modal" style={{ width: "700px" }} onClick={(e) => e.stopPropagation()}>
        <div className="modal-header">Chapter Arc Editor</div>
        <div className="modal-body arc-editor">
          <label>
            Working Title
            <input type="text" value={arc.workingTitle} onChange={(e) => update({ workingTitle: e.target.value })} />
          </label>
          <label>
            Narrative Function
            <textarea
              value={arc.narrativeFunction}
              onChange={(e) => update({ narrativeFunction: e.target.value })}
              rows={2}
            />
          </label>
          <label>
            Dominant Register
            <input
              type="text"
              value={arc.dominantRegister}
              onChange={(e) => update({ dominantRegister: e.target.value })}
            />
          </label>
          <label>
            Pacing Target
            <input type="text" value={arc.pacingTarget} onChange={(e) => update({ pacingTarget: e.target.value })} />
          </label>
          <label>
            Ending Posture
            <input type="text" value={arc.endingPosture} onChange={(e) => update({ endingPosture: e.target.value })} />
          </label>
          <ReaderStateFields
            label="Reader State Entering"
            state={arc.readerStateEntering}
            onChange={(rs) => update({ readerStateEntering: rs })}
          />
          <ReaderStateFields
            label="Reader State Exiting"
            state={arc.readerStateExiting}
            onChange={(rs) => update({ readerStateExiting: rs })}
          />
        </div>
        <div className="modal-footer">
          <button onClick={onClose}>Close</button>
        </div>
      </div>
    </div>
  );
}

// src/app/components/ChapterArcEditor.svelte
<script lang="ts">
import type { ChapterArc, ReaderState } from "../../types/index.js";
import { Button, Input, Modal, TextArea } from "../primitives/index.js";
import type { ProjectStore } from "../store/project.svelte.js";

let {
  arc,
  store,
  onClose,
}: {
  arc: ChapterArc;
  store: ProjectStore;
  onClose: () => void;
} = $props();

function update(changes: Partial<ChapterArc>) {
  store.setChapterArc({ ...arc, ...changes });
}

function updateReaderState(field: "readerStateEntering" | "readerStateExiting", rs: ReaderState) {
  update({ [field]: rs });
}

function parseCSV(value: string): string[] {
  return value
    .split(",")
    .map((s) => s.trim())
    .filter(Boolean);
}
</script>

<Modal open={true} {onClose} width="wide">
  {#snippet header()}Chapter Arc Editor{/snippet}

  <div class="arc-editor">
    <label>
      Working Title
      <Input value={arc.workingTitle} oninput={(e) => update({ workingTitle: (e.target as HTMLInputElement).value })} />
    </label>
    <label>
      Narrative Function
      <TextArea
        value={arc.narrativeFunction}
        variant="compact"
        rows={2}
        oninput={(e) => update({ narrativeFunction: (e.target as HTMLTextAreaElement).value })}
      />
    </label>
    <label>
      Dominant Register
      <Input value={arc.dominantRegister} oninput={(e) => update({ dominantRegister: (e.target as HTMLInputElement).value })} />
    </label>
    <label>
      Pacing Target
      <Input value={arc.pacingTarget} oninput={(e) => update({ pacingTarget: (e.target as HTMLInputElement).value })} />
    </label>
    <label>
      Ending Posture
      <Input value={arc.endingPosture} oninput={(e) => update({ endingPosture: (e.target as HTMLInputElement).value })} />
    </label>

    {#each [
      { label: "Reader State Entering", field: "readerStateEntering" as const, state: arc.readerStateEntering },
      { label: "Reader State Exiting", field: "readerStateExiting" as const, state: arc.readerStateExiting },
    ] as section}
      <fieldset class="arc-fieldset">
        <legend>{section.label}</legend>
        <label>Knows <Input value={section.state.knows.join(", ")} oninput={(e) => updateReaderState(section.field, { ...section.state, knows: parseCSV((e.target as HTMLInputElement).value) })} placeholder="Comma-separated items" /></label>
        <label>Suspects <Input value={section.state.suspects.join(", ")} oninput={(e) => updateReaderState(section.field, { ...section.state, suspects: parseCSV((e.target as HTMLInputElement).value) })} placeholder="Comma-separated items" /></label>
        <label>Wrong about <Input value={section.state.wrongAbout.join(", ")} oninput={(e) => updateReaderState(section.field, { ...section.state, wrongAbout: parseCSV((e.target as HTMLInputElement).value) })} placeholder="Comma-separated items" /></label>
        <label>Active tensions <Input value={section.state.activeTensions.join(", ")} oninput={(e) => updateReaderState(section.field, { ...section.state, activeTensions: parseCSV((e.target as HTMLInputElement).value) })} placeholder="Comma-separated items" /></label>
      </fieldset>
    {/each}
  </div>

  {#snippet footer()}
    <Button onclick={onClose}>Close</Button>
  {/snippet}
</Modal>

<style>
  .arc-editor { display: flex; flex-direction: column; gap: 10px; }
  .arc-editor label {
    display: flex; flex-direction: column; gap: 3px;
    font-size: 11px; color: var(--text-secondary);
    text-transform: uppercase; letter-spacing: 0.05em;
  }
  .arc-fieldset {
    border: 1px solid var(--border); border-radius: var(--radius-md); padding: 8px; margin: 0;
  }
  .arc-fieldset :global(legend) {
    font-size: 10px; text-transform: uppercase; letter-spacing: 0.1em;
    color: var(--accent); padding: 0 6px;
  }
</style>
